import { prefixObjectValues } from '../../utils/helpers'

export const PREFIX = '@@HOME/';
let types = {
  ADD_DOCUMENT: 'ADD_DOCUMENT',

  CHANGE_HASH: 'CHANGE_HASH',

  SET_DOCUMENT_METADATA: 'SET_DOCUMENT_METADATA',

  SET_CONTRACT_ERROR: 'SET_CONTRACT_ERROR',

  CLEAR_DOCUMENT_LIST: 'CLEAR_DOCUMENT_LIST',

  ADD_DOCUMENT_TO_LIST: 'ADD_DOCUMENT_TO_LIST',

  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',

  EVENT_DOCUMENT_REIGSTERED: 'EVENT_DOCUMENT_REIGSTERED',

};

types = prefixObjectValues(types, PREFIX);
export default types;